edition                      = "2018"
comment_width                = 80
wrap_comments                = true
normalize_comments           = true
error_on_line_overflow       = true
error_on_unformatted         = false
format_code_in_doc_comments  = true
format_macro_bodies          = true
format_macro_matchers        = true # $a: ident -> $a:ident
format_strings               = true
imports_granularity          = "Crate"
imports_layout               = "HorizontalVertical"
reorder_imports              = true
match_arm_blocks             = false
match_block_trailing_comma   = true
max_width                    = 100
newline_style                = "Unix"
overflow_delimited_expr      = true
reorder_impl_items           = true
struct_field_align_threshold = 20
tab_spaces                   = 4
unstable_features            = true
use_field_init_shorthand     = true
use_try_shorthand            = true
color                        = "Always"
fn_single_line               = false
struct_lit_width             = 60
struct_variant_width         = 60

combine_control_expr         = true # foo!(if x {...
